const mongoose=require('mongoose');
const schema=mongoose.Schema;
 const userSchema = new schema({
    userName:{
        type:String,
        require:true
    },
    email:{
        type:String,
        require:true
    },
    password:{
        type:String,
        require:true
    },
    Passout_date:{
        type:Date,
        require:true
    },
    Current_organisation:{
        type:String,
        require:true
    },
    picture:{
        type:String,
        require:true
    },
    Branch:{
        type:String,
        require:true
    },
    Name:{
        type:String,
        require:true
    },
    Date_of_birth:{
        type:Date,
        require:true
    }
 },{timestamps:true});
 exports.userModel=mongoose.model('users',userSchema);